/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EditorPane: typeof import('./components/ide/editor/EditorPane.vue')['default']
    EditorTabs: typeof import('./components/ide/editor/EditorTabs.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    FileTree: typeof import('./components/ide/file-tree/FileTree.vue')['default']
    FileTreeNode: typeof import('./components/ide/file-tree/FileTreeNode.vue')['default']
    GlobalLoading: typeof import('./components/common/GlobalLoading.vue')['default']
    IdeContent: typeof import('./components/ide/IdeContent.vue')['default']
    IdeLayout: typeof import('./components/ide/IdeLayout.vue')['default']
    IdeModal: typeof import('./components/ide/IdeModal.vue')['default']
    IdeOverlay: typeof import('./components/ide/IdeOverlay.vue')['default']
    IdeStatusBar: typeof import('./components/ide/common/IdeStatusBar.vue')['default']
    IpReservation: typeof import('./components/common/IpReservation.vue')['default']
    MonacoEditor: typeof import('./components/ide/editor/MonacoEditor.vue')['default']
    PortForwardDialog: typeof import('./components/vps/PortForwardDialog.vue')['default']
    ResourceBar: typeof import('./components/common/ResourceBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitPane: typeof import('./components/ide/common/SplitPane.vue')['default']
    StatusBadge: typeof import('./components/common/StatusBadge.vue')['default']
    TerminalModal: typeof import('./components/terminal/TerminalModal.vue')['default']
    TerminalPane: typeof import('./components/ide/terminal/TerminalPane.vue')['default']
    TheHeader: typeof import('./components/layout/TheHeader.vue')['default']
    TheSidebar: typeof import('./components/layout/TheSidebar.vue')['default']
  }
}
