/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/components/ApprovalsTab': RouteRecordInfo<
      '/admin/components/ApprovalsTab',
      '/admin/components/ApprovalsTab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/components/InvitationsTab': RouteRecordInfo<
      '/admin/components/InvitationsTab',
      '/admin/components/InvitationsTab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/components/UsersTab': RouteRecordInfo<
      '/admin/components/UsersTab',
      '/admin/components/UsersTab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/components/VmInstancesTab': RouteRecordInfo<
      '/admin/components/VmInstancesTab',
      '/admin/components/VmInstancesTab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docker/': RouteRecordInfo<
      '/docker/',
      '/docker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/gpu/': RouteRecordInfo<
      '/gpu/',
      '/gpu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nodes/': RouteRecordInfo<
      '/nodes/',
      '/nodes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register/': RouteRecordInfo<
      '/register/',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/stats/': RouteRecordInfo<
      '/stats/',
      '/stats',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tasks/': RouteRecordInfo<
      '/tasks/',
      '/tasks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tasks/components/TaskDetailDialog': RouteRecordInfo<
      '/tasks/components/TaskDetailDialog',
      '/tasks/components/TaskDetailDialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tasks/components/TaskSubmitDialog': RouteRecordInfo<
      '/tasks/components/TaskSubmitDialog',
      '/tasks/components/TaskSubmitDialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vps/': RouteRecordInfo<
      '/vps/',
      '/vps',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vps/components/VpsCard': RouteRecordInfo<
      '/vps/components/VpsCard',
      '/vps/components/VpsCard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vps/components/VpsCreateDialog': RouteRecordInfo<
      '/vps/components/VpsCreateDialog',
      '/vps/components/VpsCreateDialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
    }
    'src/pages/admin/components/ApprovalsTab.vue': {
      routes:
        | '/admin/components/ApprovalsTab'
      views:
        | never
    }
    'src/pages/admin/components/InvitationsTab.vue': {
      routes:
        | '/admin/components/InvitationsTab'
      views:
        | never
    }
    'src/pages/admin/components/UsersTab.vue': {
      routes:
        | '/admin/components/UsersTab'
      views:
        | never
    }
    'src/pages/admin/components/VmInstancesTab.vue': {
      routes:
        | '/admin/components/VmInstancesTab'
      views:
        | never
    }
    'src/pages/docker/index.vue': {
      routes:
        | '/docker/'
      views:
        | never
    }
    'src/pages/gpu/index.vue': {
      routes:
        | '/gpu/'
      views:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
    }
    'src/pages/nodes/index.vue': {
      routes:
        | '/nodes/'
      views:
        | never
    }
    'src/pages/register/index.vue': {
      routes:
        | '/register/'
      views:
        | never
    }
    'src/pages/stats/index.vue': {
      routes:
        | '/stats/'
      views:
        | never
    }
    'src/pages/tasks/index.vue': {
      routes:
        | '/tasks/'
      views:
        | never
    }
    'src/pages/tasks/components/TaskDetailDialog.vue': {
      routes:
        | '/tasks/components/TaskDetailDialog'
      views:
        | never
    }
    'src/pages/tasks/components/TaskSubmitDialog.vue': {
      routes:
        | '/tasks/components/TaskSubmitDialog'
      views:
        | never
    }
    'src/pages/vps/index.vue': {
      routes:
        | '/vps/'
      views:
        | never
    }
    'src/pages/vps/components/VpsCard.vue': {
      routes:
        | '/vps/components/VpsCard'
      views:
        | never
    }
    'src/pages/vps/components/VpsCreateDialog.vue': {
      routes:
        | '/vps/components/VpsCreateDialog'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
